# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package definitions
COPY package*.json ./

# Install dependencies without running lifecycle scripts (we run build manually)
RUN npm install --ignore-scripts

# Copy remaining source files
COPY . .

# Build the project
RUN npm run build

# Expose port if necessary (MCP servers usually use stdio, but keeping open for debugging)
EXPOSE 3000

# Run the MCP server
CMD [ "node", "build/index.js" ]
